name: device_bot
description: A bot running on embedded devices, using OpenAI to interpret commands.
dependencies:
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.16.2
  openai:
    url: github.com/toitware/toit-openai
    version: ^0.1.0
